# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\x12\x07\x66ilesvc\"\x1b\n\x0b\x46ileRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\'\n\tFileChunk\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"4\n\tUploadAck\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x16\n\x0e\x62ytes_received\x18\x02 \x01(\x05\x32y\n\x0b\x46ileService\x12\x36\n\x08\x44ownload\x12\x14.filesvc.FileRequest\x1a\x12.filesvc.FileChunk0\x01\x12\x32\n\x06Upload\x12\x12.filesvc.FileChunk\x1a\x12.filesvc.UploadAck(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=31
  _globals['_FILEREQUEST']._serialized_end=58
  _globals['_FILECHUNK']._serialized_start=60
  _globals['_FILECHUNK']._serialized_end=99
  _globals['_UPLOADACK']._serialized_start=101
  _globals['_UPLOADACK']._serialized_end=153
  _globals['_FILESERVICE']._serialized_start=155
  _globals['_FILESERVICE']._serialized_end=276
# @@protoc_insertion_point(module_scope)
